- updated github actions

diff --git a/.github/workflows/_build_app.yml b/.github/workflows/_build_app.yml
--- a/.github/workflows/_build_app.yml
+++ b/.github/workflows/_build_app.yml
@@ -24,15 +24,15 @@ jobs:
           path: trading_bot
       
       # verify client and server versions match
-      #- name: Verify client and server versions match
-      #  shell: bash
-      #  run: |
-      #    if ["$(jq -r '.version' ./trading_bot/package.json)" != "$(jq -r '.version' ./trading_bot_client/package.json)"]; then
-      #      echo "ERROR: Client and server versions do not match."
-      #      exit 1
-      #    else
-      #      echo "Versions match."
-      #    fi
+      - name: Verify client and server versions match
+        shell: bash
+        run: |
+          if ["$(jq -r '.version' ./trading_bot/package.json)" != "$(jq -r '.version' ./trading_bot_client/package.json)"]; then
+            echo "ERROR: Client and server versions do not match."
+            exit 1
+          else
+            echo "Versions match."
+          fi
       
       # build client
       - name: Build trading_bot_client
