- updated actions

diff --git a/.github/workflows/_build_app.yml b/.github/workflows/_build_app.yml
--- a/.github/workflows/_build_app.yml
+++ b/.github/workflows/_build_app.yml
@@ -23,22 +23,16 @@ jobs:
           ref: master
           path: trading_bot
       
-      #TODO: debug
-      - name: Setup tmate session
-        uses: mxschmitt/action-tmate@v3
-        with:
-          limit-access-to-actor: true
-      
       # verify client and server versions match
-      - name: Verify client and server versions match
-        shell: bash
-        run: |
-          if ["$(jq -r '.version' ./trading_bot/package.json)" != "$(jq -r '.version' ./trading_bot_client/package.json)"]; then
-            echo "ERROR: Client and server versions do not match."
-            exit 1
-          else
-            echo "Versions match."
-          fi
+      #- name: Verify client and server versions match
+      #  shell: bash
+      #  run: |
+      #    if ["$(jq -r '.version' ./trading_bot/package.json)" != "$(jq -r '.version' ./trading_bot_client/package.json)"]; then
+      #      echo "ERROR: Client and server versions do not match."
+      #      exit 1
+      #    else
+      #      echo "Versions match."
+      #    fi
       
       # build client
       - name: Build trading_bot_client
@@ -53,6 +47,12 @@ jobs:
         shell: bash
         run: |
           mv trading_bot_client/dist trading_bot/public/
+      
+      #TODO: debug
+      - name: Setup tmate session
+        uses: mxschmitt/action-tmate@v3
+        with:
+          limit-access-to-actor: true
       
       # upload artifacts
       - name: Upload app artifacts
